config/routes.rb
Rails.application.routes.draw do
  resources :akis

end

app/models/aki.rb
class Aki < ActiveRecord::Base
end

app/controllers/akis_controller.rb
class AkisController < ApplicationController
  before_action :set_aki, only: [:show, :edit, :update, :destroy]

  # GET /akis
  # GET /akis.json
  def index
    @akis = Aki.all
  end

  # GET /akis/1
  # GET /akis/1.json
  def show
  end

  # GET /akis/new
  def new
    @aki = Aki.new
  end

  # GET /akis/1/edit
  def edit
  end

  # POST /akis
  # POST /akis.json
  def create
    @aki = Aki.new(aki_params)

    respond_to do |format|
      if @aki.save
        format.html { redirect_to @aki, notice: 'Aki was successfully created.' }
        format.json { render :show, status: :created, location: @aki }
      else
        format.html { render :new }
        format.json { render json: @aki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akis/1
  # PATCH/PUT /akis/1.json
  def update
    respond_to do |format|
      if @aki.update(aki_params)
        format.html { redirect_to @aki, notice: 'Aki was successfully updated.' }
        format.json { render :show, status: :ok, location: @aki }
      else
        format.html { render :edit }
        format.json { render json: @aki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akis/1
  # DELETE /akis/1.json
  def destroy
    @aki.destroy
    respond_to do |format|
      format.html { redirect_to akis_url, notice: 'Aki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aki
      @aki = Aki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aki_params
      params.require(:aki).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/akis_helper.rb
module AkisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/akis/_form.html.erb
<%= form_for(@aki) do |f| %>
  <% if @aki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aki.errors.count, "error") %> prohibited this aki from being saved:</h2>

      <ul>
      <% @aki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/akis/edit.html.erb
<h1>Editing Aki</h1>

<%= render 'form' %>

<%= link_to 'Show', @aki %> |
<%= link_to 'Back', akis_path %>

app/views/akis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Akis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @akis.each do |aki| %>
      <tr>
        <td><%= aki.title %></td>
        <td><%= aki.body %></td>
        <td><%= link_to 'Show', aki %></td>
        <td><%= link_to 'Edit', edit_aki_path(aki) %></td>
        <td><%= link_to 'Destroy', aki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aki', new_aki_path %>

app/views/akis/new.html.erb
<h1>New Aki</h1>

<%= render 'form' %>

<%= link_to 'Back', akis_path %>

app/views/akis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @aki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @aki.body %>
</p>

<%= link_to 'Edit', edit_aki_path(@aki) %> |
<%= link_to 'Back', akis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akigithub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>